spring:
  profiles:
    active: dev
server:
  port: 8081
sleep: 0
swagger:
  open: true
# Nacos 注册中心客户端心跳日志禁用 get changedGroupKeys:[] 刷屏
logging:
  level:
    com.alibaba.nacos.client.config.impl: WARN
